myauth/urls.py
from django.urls import path, include
from myauth import views

app_name = 'myauth'
urlpatterns = [
    path('', views.Login.as_view(), name = 'login'),
    path('logout/', views.Logout.as_view(), name = 'logout'),
    path('top/', views.Top.as_view(), name = 'top'),
    path('signup/', views.SignUp.as_view(), name = 'add_user'),
    path('users/', views.ListUser.as_view(), name = 'list_user'),
    path('users/<str:pk>', views.Profile.as_view(), name = 'profile'),
    path('users/<str:pk>/delete', views.DeleteUser.as_view(), name = 'delete_user'),
    path('users/<str:pk>/change-password', views.ChangePassword.as_view(), name='change_password')
]

myusers/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myauth.urls'))
]

myauth/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import BaseUserManager, PermissionsMixin
from django.core.mail import send_mail
from django.utils.translation import ugettext_lazy as _
from django.core.validators import (
    RegexValidator, MaxValueValidator, MinValueValidator
)
from django.utils import timezone
class UserManager(BaseUserManager):
    """ユーザーマネージャー."""
    
    use_in_migrations = True

    def _create_user(self, user_id, password, **extra_fields):
        if not user_id:
            raise ValueError('The given user_id must be set')
        
        user = self.model(user_id = user_id, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, user_id, password=None, **extra_fields):
        """is_staff(管理サイトにログインできるか)と、is_superuer(全ての権限)をFalseに"""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(user_id, password, **extra_fields)

    def create_superuser(self, user_id, password, **extra_fields):
        """スーパーユーザーは、is_staffとis_superuserをTrueに"""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(user_id, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    """
        カスタムユーザ
    """
    def __str__(self):
        return self.user_id
    user_id = models.CharField(verbose_name = 'ユーザID', max_length = 10, primary_key = True)
    family_name = models.CharField(verbose_name = '姓', max_length = 50)
    first_name = models.CharField(verbose_name = '名', max_length = 50)
    zip = models.CharField(
        verbose_name = '郵便番号',
        max_length = 10,
        validators = [
            RegexValidator(
                regex = '\d{3}\-?\d{4}',
                message = 'フォーマットが不正です。',
            )
        ]
    )
    address = models.CharField(verbose_name = '住所', max_length = 255)
    phone = models.CharField(
        verbose_name = '電話番号',
        max_length = 20,
        validators = [
            RegexValidator(
                regex = '[0-9\-\+]+',
                message = 'フォーマットが不正です。'
            )
        ]
    )
    unnamed1 = models.IntegerField(
        null = True,
        blank = True,
        verbose_name = '名称1',
        validators = [
            MaxValueValidator(9999999999),
            MinValueValidator(0),
        ]
    )
    unnamed2 = models.IntegerField(
        null = True,
        blank = True,
        verbose_name = '名称2',
        validators = [
            MaxValueValidator(9999),
            MinValueValidator(1000),
        ]
    )
    unnamed3 = models.IntegerField(
        null = True,
        blank = True,
        verbose_name = '名称3',
        validators = [
            MaxValueValidator(9999),
            MinValueValidator(1000),
        ]
    )
    unnamed4 = models.CharField(
        null = True,
        blank = True,
        verbose_name = '名称4',
        max_length = 10,
        validators = [
            RegexValidator(
                regex = '[0-9a-zA-Z]{1:10}'
            ),
        ]
    )
    date_joined = models.DateTimeField(verbose_name = '登録日', default = timezone.now)
    is_staff = models.BooleanField(
        _('管理者'),
        default=False,
        help_text=_(
        'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('利用開始'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    USERNAME_FIELD = 'user_id'
    objects = UserManager()
    REQUIRED_FIELDS = [
        'family_name',
        'first_name',
        'zip',
        'address',
        'phone'
    ]

myauth/forms.py
from django.contrib.auth.forms import (
    AuthenticationForm, UserCreationForm, PasswordChangeForm
)
from django import forms
from .models import (
    User,
)

form_input_base_class = 'p-2 form-input block border w-full mb-5 '
class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(
        widget = forms.TextInput(
            attrs = {
                'class': form_input_base_class,
            }
        )
    )
    password = forms.CharField(
        widget = forms.PasswordInput(
            attrs = {
                'class': form_input_base_class,
            }
    )
)

class SignUpForm(UserCreationForm):
    required_css_class = 'required'
    class Meta:
        model = User
        fields = [
            'family_name', 
            'first_name', 
            'zip',
            'address',
            'phone',
            'unnamed1',
            'unnamed2',
            'unnamed3',
            'unnamed4',
            'password1', 
            'password2', 
        ]
    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = form_input_base_class

    def get_next_id(self):
        usercount = User.objects.all().count()
        return str(1000 + usercount)

    # @override
    def save(self, commit=True):
        user = super().save(commit=False)
        user.user_id = self.get_next_id()
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class ProfileForm(forms.ModelForm):
    required_css_class = 'required'
    class Meta:
        model = User
        fields = (
            'zip',
            'address',
            'phone',
            'unnamed1',
            'unnamed2',
            'unnamed3',
            'unnamed4',
        )
        
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            if visible.field.required:
                visible.field.label = f'{visible.field.label}*'
            visible.field.widget.attrs['class'] = form_input_base_class

class PasswordForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = form_input_base_class

myauth/views.py
from django.shortcuts import (
    render, redirect, get_object_or_404
)
from django.contrib.auth.mixins import (
    UserPassesTestMixin, LoginRequiredMixin
)
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView
)
from django.views.generic import (
    CreateView, UpdateView, TemplateView, ListView, DeleteView
)
from django.urls import reverse_lazy
from django.contrib import messages

from .forms import (
    LoginForm, ProfileForm, SignUpForm, PasswordForm
)
from .models import (
    User,
)

class OnlySuperuserMixin(UserPassesTestMixin):
    raise_exception = False # set True if raise 403_Forbidden

    def test_func(self):
        user = self.request.user
        return user.is_superuser

class OnlyYouOrSuperuserMixin(UserPassesTestMixin):
    raise_exception = False # set True if raise 403_Forbidden

    def test_func(self):
        user = self.request.user
        if 'pk' in self.kwargs:
            return user.pk == self.kwargs['pk'] or user.is_superuser
        else:
            return user.is_superuser

# Create your views here.
class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'myauth/login.html'

class Logout(LogoutView):
  pass

class Top(LoginRequiredMixin, TemplateView):
    template_name = 'myauth/top.html'

class Profile(OnlyYouOrSuperuserMixin, UpdateView):
    model = User
    form_class = ProfileForm
    template_name = 'myauth/profile.html'
    def get_context_data(self, **kwargs):
        ret = super().get_context_data(**kwargs)
        ret['user'] = self.request.user
        return ret

    def get(self, request, *args, **kwargs):
        print(request.user)
        return super().get(request, *args, **kwargs)

    def form_valid(self, form, **kwargs):
        ret = super().form_valid(form, **kwargs)
        messages.success(self.request, '更新しました。')
        return ret

    def get_success_url(self):
        return reverse_lazy('myauth:profile', kwargs={ 'pk': self.kwargs['pk'] })
    
class SignUp(OnlySuperuserMixin, CreateView):
    model = User
    form_class = SignUpForm
    success_url = reverse_lazy('myauth:login')
    template_name = 'myauth/signup.html'
    

    def form_valid(self, form):
        ret = super().form_valid(form)
        messages.success(self.request, f'ユーザ:{self.object.user_id} 登録完了しました。')
        return ret

class ChangePassword(OnlyYouOrSuperuserMixin, PasswordChangeView):
    template_name = 'myauth/change_password.html'
    form_class = PasswordForm
    
    def get_success_url(self):
        messages.success(self.request, 'パスワードを更新しました')
        return reverse_lazy('myauth:profile', kwargs = { 'pk': self.request.user.pk })    
    
class ListUser(OnlySuperuserMixin, ListView):
    model = User
    template_name = 'myauth/list_user.html'
    queryset = User.objects.all().order_by('pk')

class DeleteUser(OnlySuperuserMixin, DeleteView):
    model = User
    template_name = 'myauth/delete_user.html'
    success_url = reverse_lazy('myauth:list_user')
    def get_context_data(self, **kwargs):
        ret = super().get_context_data(**kwargs)
        ret['user'] = self.request.user
        return ret

myauth/templates/myauth/base.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://pagecdn.io/lib/tailwindcss/1.6.2/tailwind.css" rel="stylesheet" crossorigin="anonymous"  >
</head>
<body class="bg-gray-200 ">
    {% include 'myauth/components/navbar.html' %}
    {% if messages %}
        {% for message in messages %}
            <div class="text-center border py-2">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="container mx-auto w-full" style="height: 100%;">
        {% block content %}{% endblock %}
    </div>
<style>
    label.required::after {
        content: '*';
    }
</style>
{% block style %}{% endblock %}
<script>
    // Ajax 使う場合↓

    // function getCookie(name) {
    //     var cookieValue = null;
    //     if (document.cookie && document.cookie !== '') {
    //     var cookies = document.cookie.split(';');
    //     for (var i = 0; i < cookies.length; i++) {
    //         var cookie = jQuery.trim(cookies[i]);
    //         // Does this cookie string begin with the name we want?
    //         if (cookie.substring(0, name.length + 1) === (name + '=')) {
    //         cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
    //         break;
    //         }
    //     }
    //     }
    //     return cookieValue;
    // }

    // var csrftoken = getCookie('csrftoken');

    // function csrfSafeMethod(method) {
    //     // these HTTP methods do not require CSRF protection
    //     return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    // }

    // $.ajaxSetup({
    //     beforeSend: function (xhr, settings) {
    //         if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
    //         xhr.setRequestHeader("X-CSRFToken", csrftoken);
    //         }
    //     }
    // });

    // var type = window.location.hash.substr(1);
    // if (type) {
    //     $(`#${type}-tab`).click();
    // }
</script>

myauth/templates/myauth/change_password.html
{% extends 'myauth/base.html' %}
{% block content %}
<div class="bg-white mx-auto mt-5 p-4 shadow" style="max-width: 600px;">
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button class="p-2 bg-green-400 border-2 text-white">更新</button>
    </form>
</div>
{% endblock %}

myauth/templates/myauth/delete_user.html
{% extends 'myauth/base.html' %}
{% block content %}
<div class="bg-white mx-auto mt-5 p-4">
    <div>ユーザ {{ object.user_id }} を削除しますか？</div>
    <form method="post">
        {% csrf_token %}      
        <div class="flex items-center">
            <button type="submit" class="border bg-red-600 font-bold text-white p-2">
                削除
            </button>
            <a href="{% url 'myauth:list_user' %}" class="ml-3 py-2 border px-2">
                キャンセル
            </a>
        </div>
    </form> 
</div>
{% endblock %}

myauth/templates/myauth/list_user.html
{% extends 'myauth/base.html' %}
{% block content %}
<div class="mx-auto mt-5 p-4 w-full overflow-x-auto">
    <table class="bg-white w-full table-auto border-collapse">
        <thead>
            <tr class="border bg-gray-600 text-white">
                <th>ID</th>
                <th>登録日</th>
                <th>姓</th>
                <th>名</th>
                <th>郵便番号</th>
                <th>住所</th>
                <th>電話番号</th>
                <th>列1</th>
                <th>列2</th>
                <th>列3</th>
                <th>列4</th>
                <th>管理者</th>
                <th>操作</th>
                
            </tr>
        </thead>
        <tbody>
            {% for u in object_list %}
            <tr class="border">
                <td class="text-center px-2">{{ u.user_id }}</td>
                <td class="text-center px-2">{{ u.date_joined|date:'Y-m-d' }}</td>
                <td class="text-center px-2">{{ u.family_name }}</td>
                <td class="text-center px-2">{{ u.first_name }}</td>
                <td class="text-center px-2">{{ u.zip }}</td>
                <td class="text-center px-2">{{ u.address }}</td>
                <td class="text-center px-2">{{ u.phone }}</td>
                <td class="text-center px-2">{{ u.unnamed1 | default_if_none:'' }}</td>
                <td class="text-center px-2">{{ u.unnamed2 | default_if_none:'' }}</td>
                <td class="text-center px-2">{{ u.unnamed3 | default_if_none:'' }}</td>
                <td class="text-center px-2">{{ u.unnamed4 | default_if_none:'' }}</td>
                
                <td class="text-center px-2">
                    <input type="checkbox" disabled {% if u.is_superuser %} checked {% endif %}>
                </td>
                <td class="text-center">
                    {% if user.is_superuser %}
                    <a class="border inline-block p-1 bg-gray-600 text-white" href="{% url 'myauth:profile' u.pk %}">
                        更新
                    </a>
                    {% endif %}
                    {% if u.pk != user.pk %}
                    <a class="border inline-block p-1 bg-red-600 text-white" href="{% url 'myauth:delete_user' u.pk %}">
                        削除
                    </a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
</div>
{% endblock %}
{% block style %}
<style>
    th, td {
        white-space: nowrap;
    }
</style>
{% endblock %}

myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}
{% block content %}
<div class="bg-white mx-auto mt-5 p-4 shadow" style="max-width: 600px;">
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button class="p-2 bg-green-400 border-2 text-white">ログイン</button>
    </form>
</div>
{% endblock %}

myauth/templates/myauth/profile.html
{% extends 'myauth/base.html' %}
{% block content %}
<div class="bg-white mx-auto mt-5 p-4 shadow" style="max-width: 600px;">
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button class="p-2 bg-green-400 border-2 text-white">更新</button>
        <a href="{% url 'myauth:change_password' user.pk %}" class="p-2 bg-purple-400 border-2 text-white">パスワード変更</a>
    </form>
</div>
{% endblock %}

myauth/templates/myauth/signup.html
{% extends 'myauth/base.html' %}
{% block content %}
<div class="bg-white mx-auto mt-5 p-4 shadow" style="max-width: 600px;">
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button class="p-2 bg-green-400 border-2 text-white">登録</button>
    </form>
</div>
{% endblock %}

myauth/templates/myauth/top.html
{% extends 'myauth/base.html' %}
{% block content %}
<div class="mx-auto text-center mt-5 p-4">
    <h1>Top Pageです</h1>
    
</div>
{% endblock %}