myauth/urls.py
from django.urls import path, include
from myauth import views

app_name = 'myauth'
urlpatterns = [
    path('', views.Login.as_view(), name = 'login'),
    path('logout/', views.Logout.as_view(), name = 'logout'),
    path('top/', views.Top.as_view(), name = 'top'),
    path('signup/', views.SignUp.as_view(), name = 'add_user'),
    path('users/', views.ListUser.as_view(), name = 'list_user'),
    path('users/<str:pk>', views.Profile.as_view(), name = 'profile'),
    path('users/<str:pk>/delete', views.DeleteUser.as_view(), name = 'delete_user'),
    path('users/<str:pk>/change-password', views.ChangePassword.as_view(), name='change_password')
]

myusers/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myauth.urls'))
]

myauth/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import BaseUserManager, PermissionsMixin
from django.core.mail import send_mail
from django.utils.translation import ugettext_lazy as _
from django.core.validators import (
    RegexValidator, MaxValueValidator, MinValueValidator
)
from django.utils import timezone
class UserManager(BaseUserManager):
    """ユーザーマネージャー."""
    
    use_in_migrations = True

    def _create_user(self, user_id, password, **extra_fields):
        if not user_id:
            raise ValueError('The given user_id must be set')
        
        user = self.model(user_id = user_id, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, user_id, password=None, **extra_fields):
        """is_staff(管理サイトにログインできるか)と、is_superuer(全ての権限)をFalseに"""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(user_id, password, **extra_fields)

    def create_superuser(self, user_id, password, **extra_fields):
        """スーパーユーザーは、is_staffとis_superuserをTrueに"""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(user_id, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    """
        カスタムユーザ
    """
    def __str__(self):
        return self.user_id
    user_id = models.CharField(verbose_name = 'ユーザID', max_length = 10, primary_key = True)
    family_name = models.CharField(verbose_name = '姓', max_length = 50)
    first_name = models.CharField(verbose_name = '名', max_length = 50)
    zip = models.CharField(
        verbose_name = '郵便番号',
        max_length = 10,
        validators = [
            RegexValidator(
                regex = '\d{3}\-?\d{4}',
                message = 'フォーマットが不正です。',
            )
        ]
    )
    address = models.CharField(verbose_name = '住所', max_length = 255)
    phone = models.CharField(
        verbose_name = '電話番号',
        max_length = 20,
        validators = [
            RegexValidator(
                regex = '[0-9\-\+]+',
                message = 'フォーマットが不正です。'
            )
        ]
    )
    unnamed1 = models.IntegerField(
        null = True,
        blank = True,
        verbose_name = '名称1',
        validators = [
            MaxValueValidator(9999999999),
            MinValueValidator(0),
        ]
    )
    unnamed2 = models.IntegerField(
        null = True,
        blank = True,
        verbose_name = '名称2',
        validators = [
            MaxValueValidator(9999),
            MinValueValidator(1000),
        ]
    )
    unnamed3 = models.IntegerField(
        null = True,
        blank = True,
        verbose_name = '名称3',
        validators = [
            MaxValueValidator(9999),
            MinValueValidator(1000),
        ]
    )
    unnamed4 = models.CharField(
        null = True,
        blank = True,
        verbose_name = '名称4',
        max_length = 10,
        validators = [
            RegexValidator(
                regex = '[0-9a-zA-Z]{1:10}'
            ),
        ]
    )
    date_joined = models.DateTimeField(verbose_name = '登録日', default = timezone.now)
    is_staff = models.BooleanField(
        _('管理者'),
        default=False,
        help_text=_(
        'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('利用開始'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    USERNAME_FIELD = 'user_id'
    objects = UserManager()
    REQUIRED_FIELDS = [
        'family_name',
        'first_name',
        'zip',
        'address',
        'phone'
    ]

myauth/forms.py
from django.contrib.auth.forms import (
    AuthenticationForm, UserCreationForm, PasswordChangeForm
)
from django import forms
from .models import (
    User,
)

form_input_base_class = 'p-2 form-input block border w-full mb-5 '
class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(
        widget = forms.TextInput(
            attrs = {
                'class': form_input_base_class,
            }
        )
    )
    password = forms.CharField(
        widget = forms.PasswordInput(
            attrs = {
                'class': form_input_base_class,
            }
    )
)

class SignUpForm(UserCreationForm):
    required_css_class = 'required'
    class Meta:
        model = User
        fields = [
            'family_name', 
            'first_name', 
            'zip',
            'address',
            'phone',
            'unnamed1',
            'unnamed2',
            'unnamed3',
            'unnamed4',
            'password1', 
            'password2', 
        ]
    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = form_input_base_class

    def get_next_id(self):
        usercount = User.objects.all().count()
        return str(1000 + usercount)

    # @override
    def save(self, commit=True):
        user = super().save(commit=False)
        user.user_id = self.get_next_id()
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class ProfileForm(forms.ModelForm):
    required_css_class = 'required'
    class Meta:
        model = User
        fields = (
            'zip',
            'address',
            'phone',
            'unnamed1',
            'unnamed2',
            'unnamed3',
            'unnamed4',
        )
        
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            if visible.field.required:
                visible.field.label = f'{visible.field.label}*'
            visible.field.widget.attrs['class'] = form_input_base_class

class PasswordForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = form_input_base_class

myauth/views.py
from django.shortcuts import (
    render, redirect, get_object_or_404
)
from django.contrib.auth.mixins import (
    UserPassesTestMixin, LoginRequiredMixin
)
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView
)
from django.views.generic import (
    CreateView, UpdateView, TemplateView, ListView, DeleteView
)
from django.urls import reverse_lazy
from django.contrib import messages

from .forms import (
    LoginForm, ProfileForm, SignUpForm, PasswordForm
)
from .models import (
    User,
)

class OnlySuperuserMixin(UserPassesTestMixin):
    raise_exception = False # set True if raise 403_Forbidden

    def test_func(self):
        user = self.request.user
        return user.is_superuser

class OnlyYouOrSuperuserMixin(UserPassesTestMixin):
    raise_exception = False # set True if raise 403_Forbidden

    def test_func(self):
        user = self.request.user
        if 'pk' in self.kwargs:
            return user.pk == self.kwargs['pk'] or user.is_superuser
        else:
            return user.is_superuser

# Create your views here.
class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'myauth/login.html'

class Logout(LogoutView):
  pass

class Top(LoginRequiredMixin, TemplateView):
    template_name = 'myauth/top.html'

class Profile(OnlyYouOrSuperuserMixin, UpdateView):
    model = User
    form_class = ProfileForm
    template_name = 'myauth/profile.html'
    def get_context_data(self, **kwargs):
        ret = super().get_context_data(**kwargs)
        ret['user'] = self.request.user
        return ret

    def get(self, request, *args, **kwargs):
        print(request.user)
        return super().get(request, *args, **kwargs)

    def form_valid(self, form, **kwargs):
        ret = super().form_valid(form, **kwargs)
        messages.success(self.request, '更新しました。')
        return ret

    def get_success_url(self):
        return reverse_lazy('myauth:profile', kwargs={ 'pk': self.kwargs['pk'] })
    
class SignUp(OnlySuperuserMixin, CreateView):
    model = User
    form_class = SignUpForm
    success_url = reverse_lazy('myauth:login')
    template_name = 'myauth/signup.html'
    

    def form_valid(self, form):
        ret = super().form_valid(form)
        messages.success(self.request, f'ユーザ:{self.object.user_id} 登録完了しました。')
        return ret

class ChangePassword(OnlyYouOrSuperuserMixin, PasswordChangeView):
    template_name = 'myauth/change_password.html'
    form_class = PasswordForm
    
    def get_success_url(self):
        messages.success(self.request, 'パスワードを更新しました')
        return reverse_lazy('myauth:profile', kwargs = { 'pk': self.request.user.pk })    
    
class ListUser(OnlySuperuserMixin, ListView):
    model = User
    template_name = 'myauth/list_user.html'
    queryset = User.objects.all().order_by('pk')

class DeleteUser(OnlySuperuserMixin, DeleteView):
    model = User
    template_name = 'myauth/delete_user.html'
    success_url = reverse_lazy('myauth:list_user')
    def get_context_data(self, **kwargs):
        ret = super().get_context_data(**kwargs)
        ret['user'] = self.request.user
        return ret

myauth/templates/myauth/components/navbar.html
<div class="bg-white shadow">
    <div class="container mx-auto px-4">
        <div class="flex items-center justify-between py-4">
        <div>
            
        </div>

        <!-- <div class="hidden sm:flex sm:items-center">
            <a href="#" class="text-gray-800 text-sm font-semibold hover:text-purple-600 mr-4">Products</a>
            <a href="#" class="text-gray-800 text-sm font-semibold hover:text-purple-600 mr-4">Marketplace</a>
            <a href="#" class="text-gray-800 text-sm font-semibold hover:text-purple-600 mr-4">Partners</a>
            <a href="#" class="text-gray-800 text-sm font-semibold hover:text-purple-600">Pricing</a>
        </div> -->

        <div class="hidden sm:flex sm:items-center">
            {% if user.is_authenticated %}
            <div class="mr-1">
                ようこそ {{ user.pk }}さん
                {% if user.is_superuser %}
                [管理者]
                {% endif %}
            </div>
            <a href="{% url 'myauth:profile' user.pk %}" class="text-gray-800 text-sm font-semibold border px-4 py-2 rounded-lg hover:text-purple-600 hover:border-purple-600">ユーザ情報更新</a>
            {% if user.is_superuser %}
                <a href="{% url 'myauth:add_user' %}" class="text-gray-800 text-sm font-semibold border px-4 py-2 rounded-lg hover:text-purple-600 hover:border-purple-600">ユーザ追加</a>
                <a href="{% url 'myauth:list_user' %}" class="text-gray-800 text-sm font-semibold border px-4 py-2 rounded-lg hover:text-purple-600 hover:border-purple-600">ユーザ一覧</a>
                
            {% endif %}
            <a href="{% url 'myauth:logout' %}" class="text-gray-800 text-sm font-semibold border px-4 py-2 rounded-lg hover:text-purple-600 hover:border-purple-600">ログアウト</a>
            
            {% endif %}
            
            
        </div>

        <div class="sm:hidden cursor-pointer">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 text-purple-600" viewBox="0 0 24 24">
            <path fill="currentColor" d="M12.9499909,17 C12.7183558,18.1411202 11.709479,19 10.5,19 C9.29052104,19 8.28164422,18.1411202 8.05000906,17 L3.5,17 C3.22385763,17 3,16.7761424 3,16.5 C3,16.2238576 3.22385763,16 3.5,16 L8.05000906,16 C8.28164422,14.8588798 9.29052104,14 10.5,14 C11.709479,14 12.7183558,14.8588798 12.9499909,16 L20.5,16 C20.7761424,16 21,16.2238576 21,16.5 C21,16.7761424 20.7761424,17 20.5,17 L12.9499909,17 Z M18.9499909,12 C18.7183558,13.1411202 17.709479,14 16.5,14 C15.290521,14 14.2816442,13.1411202 14.0500091,12 L3.5,12 C3.22385763,12 3,11.7761424 3,11.5 C3,11.2238576 3.22385763,11 3.5,11 L14.0500091,11 C14.2816442,9.85887984 15.290521,9 16.5,9 C17.709479,9 18.7183558,9.85887984 18.9499909,11 L20.5,11 C20.7761424,11 21,11.2238576 21,11.5 C21,11.7761424 20.7761424,12 20.5,12 L18.9499909,12 Z M9.94999094,7 C9.71835578,8.14112016 8.70947896,9 7.5,9 C6.29052104,9 5.28164422,8.14112016 5.05000906,7 L3.5,7 C3.22385763,7 3,6.77614237 3,6.5 C3,6.22385763 3.22385763,6 3.5,6 L5.05000906,6 C5.28164422,4.85887984 6.29052104,4 7.5,4 C8.70947896,4 9.71835578,4.85887984 9.94999094,6 L20.5,6 C20.7761424,6 21,6.22385763 21,6.5 C21,6.77614237 20.7761424,7 20.5,7 L9.94999094,7 Z M7.5,8 C8.32842712,8 9,7.32842712 9,6.5 C9,5.67157288 8.32842712,5 7.5,5 C6.67157288,5 6,5.67157288 6,6.5 C6,7.32842712 6.67157288,8 7.5,8 Z M16.5,13 C17.3284271,13 18,12.3284271 18,11.5 C18,10.6715729 17.3284271,10 16.5,10 C15.6715729,10 15,10.6715729 15,11.5 C15,12.3284271 15.6715729,13 16.5,13 Z M10.5,18 C11.3284271,18 12,17.3284271 12,16.5 C12,15.6715729 11.3284271,15 10.5,15 C9.67157288,15 9,15.6715729 9,16.5 C9,17.3284271 9.67157288,18 10.5,18 Z"/>
            </svg>
        </div>
        </div>
        
        <div class="block sm:hidden bg-white border-t-2 py-2">
        <div class="flex items-center">
            {% if user.is_authenticated %}
            <div class="mr-1">
                ようこそ {{ user.pk }}さん
                {% if user.is_superuser %}
                [管理者]
                {% endif %}
            </div>
            <a href="{% url 'myauth:profile' user.pk %}" class="text-gray-800 text-sm font-semibold border px-4 py-2 rounded-lg hover:text-purple-600 hover:border-purple-600">ユーザ情報更新</a>
            {% if user.is_superuser %}
                <a href="{% url 'myauth:add_user' %}" class="text-gray-800 text-sm font-semibold border px-4 py-2 rounded-lg hover:text-purple-600 hover:border-purple-600">ユーザ追加</a>
                <a href="{% url 'myauth:list_user' %}" class="text-gray-800 text-sm font-semibold border px-4 py-2 rounded-lg hover:text-purple-600 hover:border-purple-600">ユーザ一覧</a>
                
            {% endif %}
            <a href="{% url 'myauth:logout' %}" class="text-gray-800 text-sm font-semibold border px-4 py-2 rounded-lg hover:text-purple-600 hover:border-purple-600">ログアウト</a>
            
            {% endif %}
        </div>
        </div>
    </div>
</div>